server:
  port: 8888
  servlet:
    context-path: /gateway

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service/
          predicates:
            - Path=/auth/**
        - id: application
          uri: lb://application/
          predicates:
            - Path=/app/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9999/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true