server:
  port: 8888
  servlet:
    context-path: /gateway

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
#        - id: auth-service
#          uri: lb://auth-service/
#          predicates:
#            - Path=/auth/**
        - id: booking
          uri: lb://booking/
          predicates:
            - Path=/booking/**
#          filters:
#            - AuthenticationFilter
        - id: bus
          uri: lb://bus/
          predicates:
            - Path=/bus/**
#          filters:
#            - AuthenticationFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9999/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true