server:
  port: 0
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://mysql-container:33061/ticket-booking-db?createDatabaseIfNotExist=true
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-container:9999/eureka/
