server:
  port: 0
  servlet:
    context-path: /bus

#Spring
spring:
  application:
    name: bus
  datasource:
    url: jdbc:mysql://localhost:3306/bus-db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#Eureka
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
  instance:
    preferIpAddress: true

