server:
  port: 0
  servlet:
    context-path: /bus

#Spring
spring:
  application:
    name: bus
  datasource:
    url: jdbc:mysql://mysql-container:3306/bus-db?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

#Eureka
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka-container:9999/eureka/
  instance:
    preferIpAddress: true

#Logging
logging:
  level:
    com:
      hackathon:
        - INFO
        - ERROR